
cmake_minimum_required(VERSION 3.30)

project(DailyCppModulesExamples LANGUAGES CXX)

add_subdirectory(BmpLoader)
add_subdirectory(BmpSaver)
add_subdirectory(FpsCounter)
add_subdirectory(GlmLite)
add_subdirectory(HighResTimer)
add_subdirectory(OpenGL)
add_subdirectory(PixelCopier)
add_subdirectory(PixelPainter)
add_subdirectory(TgaLoader)
add_subdirectory(WinLite)
